# Generated by Django 3.2 on 2024-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
